# Generated by Django 5.2.1 on 2025-05-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name']},
        ),
    ]
