# Generated by Django 5.2.1 on 2025-05-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
